{ self }:

{ config
, pkgs
, lib ? config.lib
, ...
}:
let
  cfg = config.CUSTOM.programs.aura-config-sync;

  inherit (lib)
    mkIf
    mkOption
    mkDefault
    mkEnableOption
    mkMerge
    types
    ;

  # ── Source paths within this flake ──
  skillsDir = "${self}/skills";
  protocolDir = "${self}/skills/protocol";
  agentsDir = "${self}/agents";
  # OpenCode agent definitions generated by the pasture codegen pipeline.
  # These are the per-role .opencode/agent/<role>.md files in the pasture
  # submodule, which carry OpenCode-flavoured YAML frontmatter (mode/model/
  # permission) wrapping the same agent body as the Claude Code agents.
  openCodeAgentsDir = "${self}/pasture/.opencode/agent";

  # ── Role definitions ──
  # Each role maps to a set of skill subdirectories with that prefix
  roleNames = [ "architect" "supervisor" "worker" "reviewer" "epoch" ];

  # Collect all .md files in a directory as an attrset: { "filename.md" = storePath; }
  # Used for flat directories (protocol docs, agent files).
  listMdFiles = dir:
    let
      entries = builtins.readDir dir;
      mdFiles = lib.filterAttrs (name: type: type == "regular" && lib.hasSuffix ".md" name) entries;
    in
    lib.mapAttrs (name: _: "${dir}/${name}") mdFiles;

  # Collect all skill subdirectories as an attrset: { "subdir-name" = storePath/SKILL.md; }
  # The new skills/ layout has one subdirectory per skill, each containing a SKILL.md file.
  listSkillFiles = dir:
    let
      entries = builtins.readDir dir;
      subdirs = lib.filterAttrs (name: type: type == "directory") entries;
    in
    lib.filterAttrs (name: path: builtins.pathExists path)
      (lib.mapAttrs (name: _: "${dir}/${name}/SKILL.md") subdirs);

  # Filter skill subdirectories by role prefix
  allSkillFiles = listSkillFiles skillsDir;

  commandsForRole = role:
    lib.filterAttrs
      (name: _: lib.hasPrefix role name)
      allSkillFiles;

  # Non-role skills (plan, status, test, feedback, explore, research, msg-*, impl-*, user-*, etc.)
  coreCommands =
    lib.filterAttrs
      (name: _:
        let
          isRoleSpecific = builtins.any (role: lib.hasPrefix role name) roleNames;
        in
        !isRoleSpecific
      )
      allSkillFiles;

  # Build the set of skill files to install based on enabled roles
  enabledCommandFiles =
    let
      roleFiles = builtins.foldl'
        (acc: role:
          if cfg.commands.roles.${role}.enable
          then acc // (commandsForRole role)
          else acc
        )
        { }
        roleNames;
    in
    coreCommands // roleFiles // cfg.commands.extraCommands;

  # ── Agent files ──
  allAgentFiles = listMdFiles agentsDir;

  enabledAgentFiles = allAgentFiles // cfg.agents.extraAgents;

in
{
  options.CUSTOM.programs.aura-config-sync = {
    enable = mkEnableOption "Aura config sync: commands, protocol docs, agents, and settings for Claude Code / OpenCode";

    # ── Packages ──
    packages = {
      enable = mkOption {
        type = types.bool;
        default = true;
        description = "Install aura-swarm (unified agent orchestration), aura-parallel (deprecated wrapper), and aura-release CLI tools";
      };
    };

    # ── Plugin skills → ~/.claude/skills/<name>/SKILL.md ──
    # Both Claude Code and OpenCode discover skills under ~/.claude/skills/.
    commands = {
      enable = mkOption {
        type = types.bool;
        default = true;
        description = "Install Aura skill SKILL.md files into ~/.claude/skills/<name>/SKILL.md (discovered by both Claude Code and OpenCode)";
      };

      roles = {
        enableAll = mkOption {
          type = types.bool;
          default = true;
          description = "Enable all agent roles. Set false to pick individual roles.";
        };
      } // (builtins.listToAttrs (map
        (role: {
          name = role;
          value = {
            enable = mkOption {
              type = types.bool;
              default = cfg.commands.roles.enableAll;
              description = "Install ${role} role commands";
            };
          };
        })
        roleNames
      ));

      extraCommands = mkOption {
        type = types.attrsOf types.path;
        default = { };
        description = "Additional command .md files to install. Keys are filenames, values are paths.";
        example = lib.literalExpression ''
          { "my-custom:command.md" = ./my-command.md; }
        '';
      };
    };

    # ── Custom agents → ~/.claude/agents/ ──
    agents = {
      enable = mkOption {
        type = types.bool;
        default = true;
        description = "Install custom agent definitions into ~/.claude/agents/";
      };

      extraAgents = mkOption {
        type = types.attrsOf types.path;
        default = { };
        description = "Additional agent .md files to install.";
      };
    };

    # ── OpenCode system-wide install ──
    # Installs pasture-generated OpenCode agent definitions to the XDG config
    # path where OpenCode discovers them system-wide.
    opencode = {
      agents = {
        enable = mkOption {
          type = types.bool;
          default = true;
          description = "Install pasture OpenCode agent definitions to ~/.config/opencode/agent/<role>.md (system-wide discovery for OpenCode)";
        };
      };
      # ~/.config/opencode/plugin/ is reserved for a future hooks plugin
      # (e.g. a bun-based .mjs hook handler). No files are installed here yet;
      # the path exists as a designated extension point per the OpenCode roadmap.
    };

    # ── Protocol docs ──
    protocol = {
      enable = mkOption {
        type = types.bool;
        default = false;
        description = "Install protocol docs (CLAUDE.md, CONSTRAINTS.md, PROCESS.md). Disabled by default since projects may have their own CLAUDE.md.";
      };

      target = mkOption {
        type = types.enum [ "global" "xdg" ];
        default = "global";
        description = "Where to install protocol docs. 'global' = ~/.claude/, 'xdg' = ~/.config/aura/protocol/";
      };
    };
  };

  config = mkIf cfg.enable (mkMerge [

    # ── Packages ──
    (mkIf cfg.packages.enable {
      home.packages = [
        self.packages.${pkgs.system}.aura-parallel
        self.packages.${pkgs.system}.aura-swarm
        self.packages.${pkgs.system}.aura-release
      ];
    })

    # ── Commands ──
    # Skills are installed to ~/.claude/skills/<name>/SKILL.md — the path both
    # Claude Code and OpenCode discover for user-level skills. The previous bare
    # ~/skills/ path was undiscoverable by either tool.
    (mkIf cfg.commands.enable {
      home.file = lib.mapAttrs'
        (name: path: {
          name = ".claude/skills/${name}/SKILL.md";
          value = { source = path; };
        })
        enabledCommandFiles;
    })

    # ── Agents ──
    (mkIf cfg.agents.enable {
      home.file = lib.mapAttrs'
        (name: path: {
          name = ".claude/agents/${name}";
          value = { source = path; };
        })
        enabledAgentFiles;
    })

    # ── OpenCode agents ──
    # Installs the pasture-generated per-role OpenCode agent definitions to
    # ~/.config/opencode/agent/<role>.md, where OpenCode discovers them
    # system-wide. The source files are the .opencode/agent/<role>.md outputs
    # from the pasture codegen pipeline (pasture/.opencode/agent/ in this flake).
    (mkIf cfg.opencode.agents.enable {
      home.file = lib.mapAttrs'
        (name: path: {
          name = ".config/opencode/agent/${name}";
          value = { source = path; };
        })
        (listMdFiles openCodeAgentsDir);
    })

    # ── Protocol docs ──
    (mkIf cfg.protocol.enable (
      let
        prefix =
          if cfg.protocol.target == "global"
          then ".claude"
          else ".config/aura/protocol";
        protocolFiles = listMdFiles protocolDir;
      in
      {
        home.file = lib.mapAttrs'
          (name: path: {
            name = "${prefix}/${name}";
            value = { source = path; };
          })
          protocolFiles;
      }
    ))
  ]);
}
